# threshold_tuning.py
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score

# Load OOF preds (generated by oof_train_shap.py)
df = pd.read_csv("results/oof_preds.csv")
y = df["target"].values
probs = df["oof_proba"].values

print("OOF AUC:", roc_auc_score(y, probs))

# Sweep thresholds from 0.1 to 0.9
thresholds = np.arange(0.1, 0.91, 0.05)
results = []

for thr in thresholds:
    y_pred = (probs >= thr).astype(int)
    prec = precision_score(y, y_pred, zero_division=0)
    rec = recall_score(y, y_pred, zero_division=0)
    f1 = f1_score(y, y_pred, zero_division=0)
    results.append((thr, prec, rec, f1))

# Convert to DataFrame for table view
res_df = pd.DataFrame(results, columns=["Threshold", "Precision", "Recall", "F1"])
print("\nThreshold tuning results:")
print(res_df.to_string(index=False, float_format="%.2f"))

# Plot curves
plt.figure(figsize=(8, 6))
plt.plot(res_df["Threshold"], res_df["Precision"], marker="o", label="Precision")
plt.plot(res_df["Threshold"], res_df["Recall"], marker="o", label="Recall")
plt.plot(res_df["Threshold"], res_df["F1"], marker="o", label="F1-score")

plt.axvline(0.35, color="red", linestyle="--", label="0.35 reference")
plt.xlabel("Threshold")
plt.ylabel("Score")
plt.title("Precision / Recall / F1 vs Threshold (OOF Predictions)")
plt.legend()
plt.grid(True)
plt.tight_layout()

# Save and show
plt.savefig("results/threshold_tuning.png", dpi=300)
print("\n📊 Saved plot to results/threshold_tuning.png")
plt.show()